@startuml catalog-service-5-2
title catalog-service - Hexagonal Architecture cible

left to right direction
skinparam shadowing false
skinparam backgroundColor #FFFFFF
skinparam defaultFontName Arial
skinparam linetype ortho
skinparam rectangle {
  RoundCorner 8
}

rectangle "Clients
REST Client\nOrder Client\nAdmin Client" as Clients #FFF7ED
rectangle "Interface Adapters
CatalogController\nCatalogAdmin" as Controllers #DBEAFE
hexagon "Business Model
Offer\nPlan\nPrice\nEligibilityRule\nCatalogVersion

Dependencies go inwards" as Domain #FFF2C6
rectangle "Ports
OfferRepository\nCatalogCache\nAuditPort" as Ports #F8FAFC
rectangle "Infrastructure Adapters
PostgreSQL Adapter\nCache Adapter\nAuditClient" as Adapters #DBEAFE
rectangle "Data Sources / External Systems
Catalog DB\nCache\naudit-service" as Targets #F8FAFC

Clients --> Controllers
Controllers --> Domain
Domain --> Ports
Ports --> Adapters
Adapters --> Targets
@enduml
