services:
  redis:
    image: redis:7.4-alpine
    container_name: cantelcox-api-gateway-redis
    network_mode: host
    command: ["redis-server", "--appendonly", "no"]

  api-gateway:
    build:
      context: .
    container_name: cantelcox-api-gateway
    network_mode: host
    env_file:
      - .env

  catalog-load-balancer:
    image: haproxy:3.0-alpine
    container_name: cantelcox-catalog-lb
    network_mode: host
    profiles:
      - load-balancing
    volumes:
      - ./infra/load-balancer/haproxy/catalog.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
